stages:
- test

test:
  stage: test
  only:
  - master
  image: ${BUILD_REGISTRY}/maven:3.6-jdk-8-slim
  variables:
    MAVEN_OPTS: >
      -Dhttps.protocols=TLSv1.2
      -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
      -Dorg.slf4j.simpleLogger.showDateTime=true
      -Djava.awt.headless=true
      -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2 -XX:MaxRAM=768m
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  cache:
    key: "${CI_COMMIT_REF_NAME}"
    paths:
    - ./.m2/repository
  before_script:
  - mkdir -p /root/.m2/
  - cp -f .m2/settings.xml /root/.m2/
  - >
    $JAVA_HOME/bin/keytool -import -noprompt -trustcacerts
    -alias nexus
    -file ./ca/ftc-ca-bundle.crt
    -keystore $JAVA_HOME/jre/lib/security/cacerts
    -storepass changeit
  script:
  - chmod +x src/test/resources/chromedriver.exe
  - mvn ${MAVEN_CLI_OPTS} test